package labWork;

public class project
{
    //private attributes
    private String projectName;
    private float maxMark;
    private projectType type;

    //constructor
    public project(String projectName, float maxMark, projectType type)
    {
        this.projectName=projectName;
        this.maxMark=maxMark;
        this.type=type;
    }
    //empty constructor
    public project(){}


    //getters and setters generated by the IDE
    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public float getMaxMark() {
        return maxMark;
    }

    public void setMaxMark(float maxMark) {
        this.maxMark = maxMark;
    }

    public projectType getType() {
        return type;
    }

    public void setType(projectType type) {
        this.type = type;
    }

    //toString() generated by the IDE
    @Override
    public String toString() {
        return "project{" +
                "projectName='" + projectName + '\'' +
                ", maxMark=" + maxMark +
                ", type=" + type +
                '}';
    }
}