import java.time.LocalDate;

public class students
{
    //private attributes
    private String name;
    private float value;
    private Long regNumber;

    //empty constructor
    public students(){}

    //constructor
    public students(String name, float age, Long regNumber)
    {
        this.name = name;
        this.value = value;
        this.regNumber = regNumber;
    }
    //getters and setters generated by the IDE
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getValue() {
        return value;
    }

    public void setValue(float value) {
        this.value = value;
    }

    public Long getRegNumber() {
        return regNumber;
    }

    public void setRegNumber(Long regNumber) {
        this.regNumber = regNumber;
    }

    //toString() function generated by IDE

    @Override
    public String toString() {
        return "students{" +
                "name='" + name + '\'' +
                ", value=" + value +
                ", regNumber=" + regNumber +
                '}';
    }
}